# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: '@ irkode'
email: 79966571+irkode@users.noreply.github.com
description: Ready to Rumble
baseurl: "" # the subpath of your site, e.g. /blog
domain: "www.irkode.de"
url: "https://www.irkode.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username: irkode

# Build settings
remote_theme: pmarsceill/just-the-docs

defaults:
  -
    scope:
      type: posts
      path: posts
    values:
      is_post: true
      layout: post
      permalink: /posts/:title/
  -
    scope:
      type: pages
      path: pages
    values:
      is_post: false
      layout: default
      permalink: /pages/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
   - _sass

exclude:
   - ./build.sh
   - .sass-cache/
   - .jekyll-cache/
   - .bundle
   - ./README.md
