name: Purge Workflows

on:
  workflow_dispatch:
    inputs:
      keep:
        description: "Keep logs newer than this days back"
        default: "30"
        required: false
      workflow:
        description: "Name of workflow (blank to purge all)"
        default: ""
        required: false

jobs:
  purge-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: irkode/purge-workflows@main
        with:
          token: ${{ github.token }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          keep: ${{ github.event.inputs.keep }}
          workflow: ${{ github.event.inputs.workflow }}
